CREATE TABLE BOOKLIST (
    NO VARCHAR(10) PRIMARY KEY
    , TITLE VARCHAR(100) NOT NULL
    , AUTHOR VARCHAR(50) NOT NULL
    , PUBLISHER VARCHAR(50)
    , STOCK NUMBER(10) DEFAULT 1
);

SELECT * FROM BOOKLIST;

CREATE SEQUENCE SEQ_BOOKLIST_NO START WITH 230001 NOCACHE;

CREATE TABLE BOOKLIST(
     NO         NUMBER(8)       PRIMARY KEY --관리번호
    ,TITLE      VARCHAR2(200)   NOT NULL
    ,AUTHOR     VARCHAR2(100)   NOT NULL
    ,PUBLISHER  VARCHAR2(100)   NOT NULL
    ,STOCK      NUMBER(20)      DEFAULT 1 --null대신 1개.
    ,STATUS     NUMBER(10)      DEFAULT 5 --대출가능    
);




COMMIT;

DROP TABLE LIBRARY_BOOKS;

INSERT INTO BOOKLIST(NO, TITLE, AUTHOR, PUBLISHER, STOCK)
            VALUES(SEQ_BOOKLIST_NO.NEXTVAL, ?, ?, ?, ?) ;

CREATE SEQUENCE SEQ_BOOKLIST_NO START WITH 230001 NOCACHE;

DROP SEQUENCE SEQ_BOOKLIST_NO;

--외래키 특강
--특정 회원이 도서를 대여했는지 알려면?
--CREATE TABLE T_차량등록 (
--    NO NUMBER(5) PRIMARY KEY
--    , CAR_ID
--    , CAR_MODEL
--    , APT_NO NUMBER(5)
--    CONSTRAINT FK_APT_NO
--    FOREIGN KEY(APT_NO)
--    REFERENCES T_입주민정보(NO)
--);


SELECT * FROM BOOKLIST ORDER BY NO;
SELECT NO, PUBLISHER, AUTHOR, TITLE, STOCK FROM BOOKLIST;

SELECT * FROM BOOKLIST WHERE NO = 230022;

INSERT INTO BOOKLIST(NO, TITLE, AUTHOR, PUBLISHER, STOCK)
            VALUES(SEQ_BOOKLIST_NO.NEXTVAL, '어떤 책이 가장 읽기 좋을까?', '김작가', '민음사', 2);
            
DELETE FROM BOOKLIST WHERE NO = 230001;

UPDATE BOOKLIST SET TITLE = '웜스10000' WHERE NO = 230007;

ROLLBACK;
            
--TITLE컬럼에서 '빛의'라는 문자를 포함한 결과를 찾으면(!=0)
SELECT * FROM BOOKLIST WHERE INSTR(TITLE, '빛의') != 0;

UPDATE BOOKLIST SET STATUS = 'true';

SELECT * FROM BOOKLIST WHERE TITLE LIKE '%빛의%';

SELECT * FROM BOOKLIST;

UPDATE BOOKLIST SET STATUS = 5;

--
CREATE TABLE MEMBER (
            MEM_NO          NUMBER(6)   NOT NULL PRIMARY KEY
          , MEM_CODE        NUMBER(1)   DEFAULT 1
          , ID              VARCHAR(20) NOT NULL
          , PW              VARCHAR(20) NOT NULL
          , NAME            VARCHAR(10)  NOT NULL
          , PHONE           VARCHAR(11) 
          , RENTAL_STATUS   VARCHAR(1)  DEFAULT 'N'
          , RENTAL_NO       VARCHAR(8)  
);

DROP TABLE MEMBER;



INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE, RENTAL_STATUS, RENTAL_NO)
            VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, ?) ;

INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE)
            VALUES(999999, 'ADMIN', '9999', '관리자', '0319999999');
            
INSERT INTO MEMBER(MEM_NO, ID, PW, NAME, PHONE)
            VALUES(SEQ_MEMBER_NO.NEXTVAL, 'hari1004', '1004', '이하리', '01010041004') ;


COMMIT;

SELECT * FROM MEMBER ORDER BY MEM_NO;

DELETE MEMBER WHERE NAME = '숩';

CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1001 NOCACHE;

DROP SEQUENCE SEQ_MEMBER_NO;

SELECT INSTR(ID, 'admin'), ID FROM MEMBER;

SELECT * FROM MEMBER WHERE ID = 'test' AND PW = '0000' ;

SELECT ID, PW, MEM_CODE FROM MEMBER WHERE ID = 'ADMIN' AND PW = '9999';

UPDATE MEMBER SET MEM_CODE = 9 WHERE ID = 'ADMIN'