CREATE TABLE BOOKLIST (
    NO VARCHAR(10) PRIMARY KEY
    , TITLE VARCHAR(100) NOT NULL
    , AUTHOR VARCHAR(50) NOT NULL
    , PUBLISHER VARCHAR(50)
    , STOCK NUMBER(10) DEFAULT 1
);

SELECT * FROM BOOKLIST;

CREATE SEQUENCE SEQ_BOOKLIST_NO START WITH 230001 NOCACHE;
